GET http://127.0.0.1:8000/api/banners HTTP/1.1 

###

GET http://127.0.0.1:8000/api/posts HTTP/1.1 

###

POST http://127.0.0.1:8000/api/signin HTTP/1.1
Content-Type: application/json

{    
    "email": "shahinalam6644@gmail.com",
    "password": "newpassword"  
}

###

POST http://127.0.0.1:8000/api/signup HTTP/1.1
Content-Type: application/json

{    
    "first_name": "shahin",
    "email": "shahinalam6644@gmail.com2",
    "password": "shahinalam6644@gmail.com2",
    "role": 1
}

###

POST http://127.0.0.1:8000/api/verifyotp HTTP/1.1
Content-Type: application/json

{        
    "email": "shahinalam6644@gmail.com",
    "otp": "1234"
}

###

POST https://larapress.org/salam/api/forgotpassword HTTP/1.1
Content-Type: application/json

{        
    "email": "shahinalam6644@gmail.com"
}

###
POST https://larapress.org/salam/api/verifyresetotp HTTP/1.1
Content-Type: application/json

{        
    "email": "shahinalam6644@gmail.com",
    "otp": "204192"
}

###
POST https://larapress.org/salam/api/resetpassword HTTP/1.1
Content-Type: application/json

{        
    "email": "shahinalam6644@gmail.com",
    "otp": "204192",
    "password": "newpassword",
    "password_confirmation": "newpassword"
}

###
GET http://127.0.0.1:8000/api/profile HTTP/1.1 
Authorization: Bearer 4|MG8LmaL4qcvLefj7a2dXRNqwT6W2pyKqgawAQEQ29ad56b1a
Content-Type: application/json

###
PUT http://127.0.0.1:8000/api/profile/update HTTP/1.1 
Authorization: Bearer 4|MG8LmaL4qcvLefj7a2dXRNqwT6W2pyKqgawAQEQ29ad56b1a
Content-Type: application/json
Accept: application/json

{
    "email": "shahinalam6644@gmail.com",
    "first_name": "John Doe Updated" 
}

###
DELETE http://127.0.0.1:8000/api/profile/delete HTTP/1.1 
Authorization: Bearer 4|MG8LmaL4qcvLefj7a2dXRNqwT6W2pyKqgawAQEQ29ad56b1a
Content-Type: application/json
Accept: application/json









 

###

POST https://larapress.org/salam/api/signin HTTP/1.1
Content-Type: application/json

{    
    "email": "shahinalam6644@gmail.com",
    "password": "shahinalam6644@gmail.com"  
}

###

POST https://larapress.org/salam/api/signup HTTP/1.1
Content-Type: application/json

{    
    "first_name": "shahin",
    "email": "shahinalam6644@gmail.com",
    "password": "shahinalam6644@gmail.com",
    "role": 1
}

###

POST https://larapress.org/salam/api/verifyotp HTTP/1.1
Content-Type: application/json

{        
    "email": "shahinalam6644@gmail.com",
    "otp": "1234"
}












###
GET https://larapress.org/salam/api/profile HTTP/1.1 
Authorization: Bearer 5|FdNhpONm1qMTuKOiDjDsn06LhNCoxe4QZbgXE3ahd2e21746
Content-Type: application/json

###
POST https://larapress.org/salam/api/profile/update HTTP/1.1 
Authorization: Bearer 5|FdNhpONm1qMTuKOiDjDsn06LhNCoxe4QZbgXE3ahd2e21746
Content-Type: application/json
Accept: application/json

{
    "email": "shahinalam6644@gmail.com",
    "first_name": "John",
    "last_name": "Doe"
}


###

POST https://larapress.org/salam/api/profile/delete HTTP/1.1 
Authorization: Bearer 5|FdNhpONm1qMTuKOiDjDsn06LhNCoxe4QZbgXE3ahd2e21746
Content-Type: application/json
Accept: application/json






